version: '3'
services: 
    postgres:
        restart: always
        image: 'postgres'
        environment: 
            - POSTGRES_PASSWORD=postgres_password
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - '3050:80'
        depends_on: 
            - api
            - client
    redis:
        image: 'redis:latest'        
    api:
        depends_on: 
            - postgres
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
                - /app/node_modules
                - ./server:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    client: 
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./client
    worker: 
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379